/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
import Models.Models.*;
import Models.Models.Crud.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Fer
 */
public class VentanaAñadirCD extends javax.swing.JFrame {

    CancionCrud Datoscancion = new CancionCrud();
    ArtistaCrud Datosartista = new ArtistaCrud();
    CompañiaCrud Datoscompañia = new CompañiaCrud();
    
    public VentanaAñadirCD() {
        List<String> Slcan = new ArrayList<>();
        List<Cancion> Lcann = new ArrayList<>();
        try {
            initComponents();
            List<Artista> Lart = Datosartista.ListaDeArtistas();
            List<Cancion> Lcan = Datoscancion.ListaDeCancions();
            List<Compañia> Lcomp = Datoscompañia.ListaDeCompañias();
            Lcann = Lcan;
        } catch (Exception ex) {
            Logger.getLogger(VentanaAñadirCD.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i =0; i < Lcann.size(); i++){
                Slcan.add(i, Lcann.get(0).toString());
            }
    }
     public void Llenarlistas(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        p2 = new javax.swing.JPanel();
        TextCrearCD = new javax.swing.JLabel();
        Text_Nombre = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        Text_canciones = new javax.swing.JLabel();
        Text_Artsita_grutpo = new javax.swing.JLabel();
        Text_compañia = new javax.swing.JLabel();
        ComboCanciones = new javax.swing.JComboBox<>();
        ComboArtista = new javax.swing.JComboBox<>();
        ComboCompañia = new javax.swing.JComboBox<>();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextCrearCD.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TextCrearCD.setText("Crear CD");

        Text_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_Nombre.setText("Nombre ");

        Text_canciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_canciones.setText("Canciones");

        Text_Artsita_grutpo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_Artsita_grutpo.setText("Artista/Grupo");

        Text_compañia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_compañia.setText("Compañia");

        ComboArtista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComboCompañia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_Nombre)
                    .addComponent(Text_compañia)
                    .addComponent(Text_Artsita_grutpo)
                    .addComponent(Text_canciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextoNombre)
                            .addComponent(ComboCanciones, 0, 125, Short.MAX_VALUE)))
                    .addComponent(ComboArtista, 0, 126, Short.MAX_VALUE)
                    .addComponent(ComboCompañia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(TextCrearCD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TextCrearCD)
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Nombre)
                    .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_canciones)
                    .addComponent(ComboCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_Artsita_grutpo)
                    .addComponent(ComboArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_compañia)
                    .addComponent(ComboCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAñadirCD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboArtista;
    private javax.swing.JComboBox<Cancion> ComboCanciones;
    private javax.swing.JComboBox<String> ComboCompañia;
    private javax.swing.JLabel TextCrearCD;
    private javax.swing.JLabel Text_Artsita_grutpo;
    private javax.swing.JLabel Text_Nombre;
    private javax.swing.JLabel Text_canciones;
    private javax.swing.JLabel Text_compañia;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel p2;
    // End of variables declaration//GEN-END:variables
}
