/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package Main;
import Models.Models.*;
import Models.Models.Crud.*;
import java.text.SimpleDateFormat;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Fer
 */
public class VentanaCancion extends javax.swing.JPanel {
    CancionCrud Datoscancion = new CancionCrud();
    CompañiaCrud Datoscompañia = new CompañiaCrud();
    CDCrud Datoscd = new CDCrud();
    ArtistaCrud Datosartista = new ArtistaCrud();
    List<String> Lcompañias = new ArrayList<>();
    List<Compañia> compañiasobject = new ArrayList<>();
    List<CD> cdobject = new ArrayList<>();
    List<String> LCD = new ArrayList<>();
   
    /** Creates new form VentanaCancion */
    public VentanaCancion() {
        initComponents();
       
        try {
            Lcompañias = Datoscompañia.ListaNombreCompañias();
            compañiasobject = Datoscompañia.ListaDeCompañias();
            LCD= Datoscd.ListaNombreCD();
            cdobject = Datoscd.ListaDeCDs();
        } catch (Exception ex) {
            Logger.getLogger(VentanaAñadir.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < Lcompañias.size(); i++) {
            Compañia_combo.addItem(Lcompañias.set(i, toString()));
        }
        for (int j = 0; j < LCD.size();j++){
            ComboCD.addItem(LCD.set(j, toString()));
        }
    }
    
    
    

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nombre_text = new javax.swing.JTextField();
        Clave_text = new javax.swing.JTextField();
        Precio_text = new javax.swing.JTextField();
        Duracion_text = new javax.swing.JTextField();
        AñadirButtonn = new javax.swing.JButton();
        Compañia_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ComboCD = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(253, 392));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Crear Cancion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Clave");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Precio");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Compañia");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Duracion");

        Precio_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_textActionPerformed(evt);
            }
        });

        AñadirButtonn.setText("Añadir");
        AñadirButtonn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirButtonnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("CD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Duracion_text)
                                .addComponent(Compañia_combo, 0, 105, Short.MAX_VALUE)
                                .addComponent(ComboCD, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(3, 3, 3))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Precio_text, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 3, Short.MAX_VALUE))
                                .addComponent(Clave_text)
                                .addComponent(Nombre_text)))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(AñadirButtonn)
                        .addGap(89, 89, 89))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Clave_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Precio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Compañia_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Duracion_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(AñadirButtonn)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Precio_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_textActionPerformed

    private void AñadirButtonnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirButtonnActionPerformed
        Cancion newcancion =new Cancion();
        String Nombre = Nombre_text.getText();
        String Clave = Clave_text.getText();
        String Precio;
        Float precio =Float.parseFloat(Precio_text.getText());
        Float duracion = Float.parseFloat(Duracion_text.getText());
        Date fecha1 = new Date();
        SimpleDateFormat dateformatt = new SimpleDateFormat("dd-MM-yyyy");
        String compñi = (String) Compañia_combo.getSelectedItem();
        int posicion = Compañia_combo.getSelectedIndex();
        int pcd = ComboCD.getSelectedIndex();
        //Agregar valores
        newcancion.setTitulo(Nombre);
        newcancion.setClave(Clave);
        newcancion.setPrecio(precio);
        newcancion.setDuracion(duracion);
        newcancion.setFechaCreacion(dateformatt.format(fecha1));
        newcancion.setCompañias(compañiasobject.get(posicion));
        newcancion.setCd(cdobject.get(pcd));
        JOptionPane.showMessageDialog(this, "Se añadio una cancion");
        
        
        
        
        try {
            //Insertar cancion en la lista de canciones
            Datoscancion.agregarCancion(newcancion);
        } catch (Exception ex) {
            Logger.getLogger(VentanaCancion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_AñadirButtonnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirButtonn;
    private javax.swing.JTextField Clave_text;
    private javax.swing.JComboBox<String> ComboCD;
    private javax.swing.JComboBox<String> Compañia_combo;
    private javax.swing.JTextField Duracion_text;
    private javax.swing.JTextField Nombre_text;
    private javax.swing.JTextField Precio_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

}
