/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.BorderLayout;
import Main.*;
import Main.VentanaAñadirObra;

/**
 *
 * @author Fer
 */
public class VentanaAñadir extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAñadir
     */
    public VentanaAñadir() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAñadirCosas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonCanciones = new javax.swing.JButton();
        BotonCD = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout PanelAñadirCosasLayout = new javax.swing.GroupLayout(PanelAñadirCosas);
        PanelAñadirCosas.setLayout(PanelAñadirCosasLayout);
        PanelAñadirCosasLayout.setHorizontalGroup(
            PanelAñadirCosasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelAñadirCosasLayout.setVerticalGroup(
            PanelAñadirCosasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Añadir");

        BotonCanciones.setText("CD");
        BotonCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancionesActionPerformed(evt);
            }
        });

        BotonCD.setText("Cancion");
        BotonCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelAñadirCosas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 62, Short.MAX_VALUE)
                        .addComponent(BotonCanciones)
                        .addGap(50, 50, 50)
                        .addComponent(BotonCD)
                        .addGap(68, 68, 68))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCD)
                    .addComponent(BotonCanciones))
                .addGap(18, 18, 18)
                .addComponent(PanelAñadirCosas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancionesActionPerformed
        VentanaCD p1 =new VentanaCD();
        p1.setSize(253, 392);
        p1.setLocation(0, 0);
        
        PanelAñadirCosas.removeAll();
        PanelAñadirCosas.add(p1,BorderLayout.CENTER);
        PanelAñadirCosas.revalidate();
        PanelAñadirCosas.repaint();
    }//GEN-LAST:event_BotonCancionesActionPerformed

    private void BotonCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCDActionPerformed
         VentanaCancion p2 =new VentanaCancion();
        p2.setSize(253, 392);
        p2.setLocation(0, 0);
        
        PanelAñadirCosas.removeAll();
        PanelAñadirCosas.add(p2,BorderLayout.CENTER);
        PanelAñadirCosas.revalidate();
        PanelAñadirCosas.repaint();
    }//GEN-LAST:event_BotonCDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAñadir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCD;
    private javax.swing.JButton BotonCanciones;
    public static javax.swing.JPanel PanelAñadirCosas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
