/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Models.Models.Crud.*;
import Models.Models.Crud.ObraCrud;
import Models.Models.Crud.CancionCrud;
import Models.Models.Cancion;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Models.Models.Compañia;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author Fer
 */
public class VentanaAñadirObra extends javax.swing.JFrame {

    ObraCrud Datosobra = new ObraCrud();
    CancionCrud Datoscancion = new CancionCrud();
    CompañiaCrud Datoscompañia = new CompañiaCrud();
    Compañia elementoscompañia = new Compañia();
    
    
    /*ArrayList<Compañia> Lcompañias = new ArrayList<>();
     */
    List<String> Lcompañias = new ArrayList<>();
    List<Compañia> compañiasobject = new ArrayList<>();
    public VentanaAñadirObra() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        TextTitulo = new javax.swing.JLabel();
        Nombre_obra = new javax.swing.JTextField();
        Clave = new javax.swing.JLabel();
        Clave_tex = new javax.swing.JTextField();
        Precio7 = new javax.swing.JLabel();
        Precio_text = new javax.swing.JTextField();
        Compañia = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        AñadirObra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Duracion_text = new javax.swing.JTextField();
        ComboCompañia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        p1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                p1ComponentAdded(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nombre.setText("Nombre");

        TextTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TextTitulo.setText("Crear Cancion");

        Nombre_obra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_obraActionPerformed(evt);
            }
        });

        Clave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Clave.setText("Clave");

        Precio7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Precio7.setText("Precio");

        Compañia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Compañia.setText("Compañia");

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        AñadirObra.setText("Añadir");
        AñadirObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirObraActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Duracion");

        ComboCompañia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCompañiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(Nombre_obra))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Precio7)
                                    .addComponent(Clave)
                                    .addComponent(Nombre))
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboCompañia, 0, 123, Short.MAX_VALUE)
                                            .addComponent(Duracion_text)))
                                    .addGroup(p1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Precio_text, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Clave_tex)))))
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Compañia)
                                    .addGroup(p1Layout.createSequentialGroup()
                                        .addComponent(AñadirObra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addGap(0, 2, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TextTitulo)
                .addGap(41, 41, 41))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TextTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(Nombre_obra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Clave)
                    .addComponent(Clave_tex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Precio7)
                    .addComponent(Precio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Compañia)
                    .addComponent(ComboCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Duracion_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AñadirObra)
                    .addComponent(Cancelar))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void LlenarLcompañias() {
        try {
            Lcompañias = Datoscompañia.ListaNombreCompañias();
        } catch (Exception ex) {
            Logger.getLogger(VentanaAñadirObra.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            compañiasobject = Datoscompañia.ListaDeCompañias();
        } catch (Exception ex) {
            Logger.getLogger(VentanaAñadirObra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    public void combocompañia() {
        for (int i = 0; i < Lcompañias.size(); i++) {
            ComboCompañia.addItem(Lcompañias.set(i, toString()));
        }
        
    }
    private void AñadirObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirObraActionPerformed
        // TODO add your handling code here:
        Cancion newcancion = new Cancion();
        String NombreText = Nombre_obra.getText();
        String ClaveText = Clave_tex.getText();
        /*String Preciotext = Precio_text.getText();
        /*Float PrecioFloat = Float.valueOf(Preciotext);
        String Duraciontet = Duracion_text.getText();
        Float DuraFloat = Float.valueOf(Duraciontet);*/
        Date fecha1 = new Date();
        SimpleDateFormat dateformatt = new SimpleDateFormat("dd-MM-yyyy");
        
        newcancion.setTitulo(NombreText);
        newcancion.setClave(ClaveText);
        newcancion.setFechaCreacion(dateformatt.format(fecha1));
       
        if (ClaveText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo de clave, no puede estar vacío");
        }
        try {
            Datoscancion.agregarCancion(newcancion);
            
            JOptionPane.showMessageDialog(null, "Se ha registrado la cancion con exito");
        } catch (Exception ex) {
            Logger.getLogger(VentanaAñadirObra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AñadirObraActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void p1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_p1ComponentAdded
        // TODO add your handling code here:

        /*-----------------------------------------------------------*/
    }//GEN-LAST:event_p1ComponentAdded

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LlenarLcompañias();
        combocompañia();
    }//GEN-LAST:event_formWindowOpened

    private void ComboCompañiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCompañiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCompañiaActionPerformed

    private void Nombre_obraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_obraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_obraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAñadirObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Prueba */

        try {
            CompañiaCrud Datoscompañia = new CompañiaCrud();
            List<Compañia> Lcompañia = Datoscompañia.ListaDeCompañias();

        } catch (Exception ex) {
            Logger.getLogger(VentanaAñadirObra.class.getName()).log(Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAñadirObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirObra;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Clave;
    private javax.swing.JTextField Clave_tex;
    private javax.swing.JComboBox<String> ComboCompañia;
    private javax.swing.JLabel Compañia;
    private javax.swing.JTextField Duracion_text;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField Nombre_obra;
    private javax.swing.JLabel Precio7;
    private javax.swing.JTextField Precio_text;
    private javax.swing.JLabel TextTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel p1;
    // End of variables declaration//GEN-END:variables
}
