/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;

import Models.Models.CD;
import Models.Models.Compañia;
import Models.Models.Crud.ArtistaCrud;
import Models.Models.Crud.CDCrud;
import Models.Models.Crud.CancionCrud;
import Models.Models.Crud.CompañiaCrud;
import java.util.ArrayList;
import java.util.List;
import Models.Models.*;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fer
 */
public class VentanaCD extends javax.swing.JPanel {
      CancionCrud Datoscancion = new CancionCrud();
    CompañiaCrud Datoscompañia = new CompañiaCrud();
    CDCrud Datoscd = new CDCrud();
    ArtistaCrud Datosartista = new ArtistaCrud();
    List<String> Lcompañias = new ArrayList<>();
    List<Compañia> compañiasobject = new ArrayList<>();
    List<Artista> artistaobject = new ArrayList<>();
    List<String> Lartis = new ArrayList<>();
    List<Cancion> cancionobject = new ArrayList<>();
    List<String> Lcan = new ArrayList<>();
    /**
     * Creates new form VentanaCD
     */
    public VentanaCD() {
        initComponents();
          try {
              Lartis = Datosartista.ListaNombreArtista();
              artistaobject = Datosartista.ListaDeArtistas();
              Lcompañias = Datoscompañia.ListaNombreCompañias();
              compañiasobject = Datoscompañia.ListaDeCompañias();
              cancionobject = Datoscancion.ListaDeCancions();
              Lcan = Datoscancion.ListaNombreCanciones();
          } catch (Exception ex) {
              Logger.getLogger(VentanaCD.class.getName()).log(Level.SEVERE, null, ex);
          }
          for (int i = 0; i < Lcompañias.size(); i++) {
            ComboCOmpañia.addItem(Lcompañias.set(i, toString()));
        }
          for (int j = 0; j < Lartis.size(); j++) {
            ComboArtista.addItem(Lartis.set(j, toString()));
        }
          for (int k = 0; k < Lcan.size(); k++) {
            ComboCancion.addItem(Lcan.set(k, toString()));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nombre_text = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ComboArtista = new javax.swing.JComboBox<>();
        ComboCOmpañia = new javax.swing.JComboBox<>();
        ComboCancion = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Nocd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Precio_text = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Crear CD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cancion");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Artista/Grupo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Compañia");

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jLabel6.setText("Numero CD");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nocd)
                                    .addComponent(Nombre_text)
                                    .addComponent(ComboCancion, 0, 108, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ComboArtista, 0, 108, Short.MAX_VALUE)
                                    .addComponent(ComboCOmpañia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Precio_text)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Nocd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ComboArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboCOmpañia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Precio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CD newcd = new CD();
        String Name = Nombre_text.getText();
        String cdno = Nocd.getText();
        int ncd = Integer.parseInt(cdno);
        int pcan = ComboCancion.getSelectedIndex();
        int part = ComboArtista.getSelectedIndex();
        int pcom = ComboCOmpañia.getSelectedIndex();
        Float precio = Float.parseFloat(Precio_text.getText());
        
        
        //Agregar los valores
        newcd.setTitulo(Name);
        newcd.setNocd(ncd);
        newcd.setPrecio(precio);
        newcd.setClave(cdno);
        newcd.setCompañias(compañiasobject.get(pcom));
        newcd.setCanciones(cancionobject.get(pcan));
        newcd.setArtistaz(artistaobject.get(part));
          try {
              //agregarlos a la lista
              Datoscd.agregarCD(newcd);
          } catch (Exception ex) {
              Logger.getLogger(VentanaCD.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboArtista;
    private javax.swing.JComboBox<String> ComboCOmpañia;
    private javax.swing.JComboBox<String> ComboCancion;
    private javax.swing.JTextField Nocd;
    private javax.swing.JTextField Nombre_text;
    private javax.swing.JTextField Precio_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
